### ISSUE TITLE
Incompatibility with PlotSquared v6

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/Plot2Dynmap#31]
### Server Implementation

Tested against Airplane Purpur branch but also affects all other Paper derivatives. 

### Server Version

1.16.5

### Describe the bug

Going around testing plugins before 1.17's release and forced Java 16 update. Figured I'd let you know of this small incompatibility probably known about before v6's release.

```
[14:04:52] [Craft Scheduler Thread - 21 - Plot2Dynmap/WARN]: [Plot2Dynmap] Plugin Plot2Dynmap v5.2 generated an exception while executing task 6474
java.lang.NoSuchMethodError: 'boolean com.plotsquared.core.PlotSquared.hasPlotArea(java.lang.String)'
	at com.empcraft.plot2dynmap.Main.run(Main.java:194) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Airplane-"1cf4e79"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Airplane-"1cf4e79"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Airplane-"1cf4e79"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

### To Reproduce

1. Install PlotSquared v6
2. Install Plot2Dynmap
3. Incompatibility.

### Expected behaviour

Compatibility with v6 P2.

### Plot Debugpaste

Irrelevant to report.

### Plot2Dynmap Version

Plot2Dynmap dev 48

### Checklist

- [] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/1292/ and the issue still persists.

**Comment by NotMyFault** [comment]
Don't modify the template.
